### ISSUE TITLE
【建议】能否增加报告导出功能？

### ISSUE THREAD

**Issue by en0th** [al0ne/LinuxCheck#13]
一方面，在日常的应急项目中，希望能够快速导出当前机器的审查结果。
另一方面，有些情况下没有办法传递脚本，希望可以能出一个包含所有测试项的表格，可以更加方便记录工作量。
表格中提供测试大项描述、小项描述、具体执行命令、结果截图。

**Comment by hoochanlon** [comment]
shell有这样的工具库就好办。不过，我倒是在Windows上写了个基线，用PowerShell大致完成你所说的表格报告

https://github.com/hoochanlon/ihs-simple/blob/main/README.md#windows桌面技术基线检查

如示

![catch2023-06-09 21 37 37](https://github.com/al0ne/LinuxCheck/assets/35732922/4d8a1b50-6b95-4223-9a35-eeed3a7dbe09)

![catch2023-06-09 21 38 47](https://github.com/al0ne/LinuxCheck/assets/35732922/9088d032-061e-4b57-98bb-1ab393f8ecbe)

**Comment by en0th** [comment]
Cool! 这正是我需要的。
