### ISSUE TITLE
运行后的一点小问题

### ISSUE THREAD

**Issue by lupus721** [al0ne/LinuxCheck#2]
root@k:~/LinuxCheck# ./LinuxCheck.sh

 =========================================================
 \                 Linux信息搜集脚本 V1.2                 /
 =========================================================
 # 支持Centos、Debian系统检测
 # author：al0ne

[+]系统改动

直接使用curl或者运行sh脚本，直接这么提示，然后就结束了？也没个报错或者log输出之类的

**Comment by al0ne** [comment]
好的，提供下你详细操作系统版本、环境是否联网，我回去测试下

**Comment by lupus721** [comment]
Linux k 4.19.0-kali1-amd64 #1 SMP Debian 4.19.13-1kali1 (2019-01-03) x86_64 GNU/Linux
Kali GNU/Linux Rolling
kali 2019.1 版本，联网状态
