### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by zhangk64** [al0ne/LinuxCheck#4]
![image](https://user-images.githubusercontent.com/29709035/61020356-0b529f80-a3d0-11e9-8eee-159fae0f33ab.png)

**Comment by al0ne** [comment]
贴个uname -a 再看看/etc/os-release 文件内容

**Comment by zhangk64** [comment]
> 贴个uname -a 再看看/etc/os-release 文件内容

![image](https://user-images.githubusercontent.com/29709035/61026810-08af7480-a3e7-11e9-96e8-512b7e6cded3.png)

**Comment by al0ne** [comment]
好的 我找个centos7的vps测试测试

**Comment by zhangk64** [comment]
> 好的 我找个centos7的vps测试测试

我之前试了debain也不行，原因是没有os-release这个文件，建议师傅提高一下兼容性。

**Comment by zhangk64** [comment]
> 好的 我找个centos7的vps测试测试

我都是在虚拟机里测试的
