### ISSUE TITLE
small fix & suggestion

### ISSUE THREAD

**Issue by starnightcyber** [al0ne/LinuxCheck#8]
内存占用排序，应该是 -k4，应该是忘记改参数了
https://github.com/al0ne/LinuxCheck/blob/833beaf71577efcc5e5adac8baff7a30b8626a78/LinuxCheck.sh#L141

另外，提个小建议：
代码中有很多输出字体颜色标记，可以封装成 print_msg 函数，这样可以简化代码，增加可读性，类似于如下。
```
#!/bin/bash

print_msg() {
  echo -e "\e[00;31m[+]$1\e[00m"
}

print_msg 'hello'
```

last but not least，很棒的实现，学到很多，shell 6 的起飞 🛫

**Comment by al0ne** [comment]
NBNB  我试试 感谢反馈
